apps:

  - id: pgvector
    name: pgvector
    image: pgvector/pgvector:pg16
    bundlePlanID: standard
    planID: small-g2

    disks:
      - name: "data"
        mountTo: /var/lib/postgresql/data
        size: 50
        maxSize: 2

    port: 5432

    envs:
      POSTGRES_DB: "mydb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
