apps:
  - id: "prestashop"
    name: "PrestaShop"
    image: "prestashop/prestashop:8.2.0"
    bundlePlanID: "standard"
    planID: "small-g2"
    port: 80

    disks:
      - name: "data"
        mountTo: "/var/www/html"
        size: "50"
        maxSize: "5" 

    envs:
      PS_DEV_MODE: "0"
      PS_HOST_MODE: "1"
      PS_INSTALL_DB: "0"
      PS_INSTALL_AUTO: "1"
      PS_ENABLE_SSL: "1"

      PS_DOMAIN: "$APP_NAME.liara.run"

      PS_FOLDER_ADMIN: "admin"

      ADMIN_MAIL: "admin@prestashop.com"
      ADMIN_PASSWD: "$RANDOM_STRING"
      
      PS_HANDLE_DYNAMIC_DOMAIN: "1"
      DB_SERVER: "$DB_main_HOST"
      DB_USER: "$DB_main_USER"
      DB_PASSWD: "$DB_main_PASSWORD"
      DB_NAME: "$DB_main_NAME"

databases:
  - type: "mysql"
    id: "main"
    version: "8.0.30"
    bundlePlanID: "standard"
    planID: "medium-g2"
