apps:
  - id: "prestashop"
    name: "PrestaShop"
    image: "prestashop/prestashop:8"
    bundlePlanID: "standard"
    planID: "medium-g2"
    port: 80
    disks:
      - name: "data"
        mountTo: "/var/www/html"
    envs:
      PS_HOST_MODE: "1"
      PS_INSTALL_DB: "0"
      PS_ENABLE_SSL: "1"
      PS_INSTALL_AUTO: "1"
      PS_DOMAIN: "$APP_NAME.liara.run"
      PS_HANDLE_DYNAMIC_DOMAIN: "1"
      ADMIN_MAIL: "admin@prestashop.com"
      ADMIN_PASSWD: "befed8f8-7e34-4674-b459-cb6eebb798f0"
      DB_USER: "$DB_main_USER"
      DB_PASSWD: "$DB_main_PASSWORD"
      DB_SERVER: "$DB_main_HOST"
      DB_NAME: "$DB_main_NAME"

databases:
  - type: "mysql"
    id: "main"
    version: "8.0.30"
    bundlePlanID: "standard"
    planID: "medium-g2"
