apps:
  - id: kutt
    name: kutt
    image: kutt/kutt:v2.7.4
    bundlePlanID: standard
    planID: small-g2
    port: 3000

    envs:
      PORT: "3000"

      DB_HOST: "$DB_main_HOST"
      DB_PORT: "$DB_main_PORT"
      DB_NAME: "postgres"
      DB_USER: "$DB_main_USER"
      DB_PASSWORD: "$DB_main_PASSWORD"
      DB_SSL: "false"

      REDIS_HOST: "$DB_base_HOST"
      REDIS_PORT: "$DB_base_PORT"
      REDIS_PASSWORD: "$DB_base_PASSWORD"

      DISALLOW_REGISTRATION: "false"
      DISALLOW_ANONYMOUS_LINKS: "false"

      USER_LIMIT_PER_DAY: "50"
      NON_USER_COOLDOWN: "0"
      DEFAULT_MAX_STATS_PER_LINK: "5000"
      CUSTOM_DOMAIN_USE_HTTPS: "true"
      JWT_SECRET: "$RANDOM_STRING"
      ADMIN_EMAILS: "admin@example.com"
      CONTACT_EMAIL: "admin@example.com"

      SITE_NAME: "Kutt"
      DEFAULT_DOMAIN: "$APP_NAME.liara.run"
      LINK_LENGTH: "6"

      MAIL_HOST: "smtp.c1.liara.email"
      MAIL_PORT: "587"
      MAIL_SECURE: "false"
      MAIL_USER: ""
      MAIL_FROM: ""
      MAIL_PASSWORD: ""


databases:
  - type: postgres
    id: main
    version: '15.4'
    bundlePlanID: standard
    planID: small-g2

  - type: redis
    id: base
    version: 7.2.3
    bundlePlanID: standard
    planID: small-g2