apps:
  - id: kutt
    name: kutt
    image: kutt/kutt:v3.2.3
    bundlePlanID: standard
    planID: small-g2
    port: 3000

    disks:
    - name: custom
      mountTo: /kutt/custom
      size: 10
      maxSize: 0.5
    - name: database
      mountTo: /kutt/db
      size: 10
      maxSize: 0.5

    envs:
      JWT_SECRET: $RANDOM_STRING
      PORT: '3000'
      SITE_NAME: Kutt
      DEFAULT_DOMAIN: $APP_NAME.liara.run
      CUSTOM_DOMAIN_USE_HTTPS: 'true'
      LINK_LENGTH: '5'
      DISALLOW_ANONYMOUS_LINKS: 'true'
      DISALLOW_REGISTRATION: 'false'
      DB_CLIENT: better-sqlite3
      DB_FILENAME: db/data
      CONTACT_EMAIL: admin@example.com
      REPORT_EMAIL: admin@example.com
      MAIL_ENABLED: 'false'
      MAIL_HOST: smtp.c1.liara.email
      MAIL_PORT: '587'
      MAIL_SECURE: 'false'
      MAIL_USER: ''
      MAIL_FROM: ''
      MAIL_PASSWORD: ''