apps:
  - id: strapi
    name: Strapi
    image: registry.c2.liara.ir/one-click-apps/strapi:node18
    bundlePlanID: standard
    planID: small-g2
    disks:
      - name: data
        mountTo: /opt/app/
        size: 10
        maxSize: 5
    port: 1337
    envs:
      HOST: 0.0.0.0
      PORT: '1337'
      DATABASE_CLIENT: mysql
      DATABASE_HOST: $DB_main_HOST
      DATABASE_PORT: $DB_main_PORT
      DATABASE_NAME: $DB_main_NAME
      DATABASE_USERNAME: $DB_main_USER
      DATABASE_PASSWORD: $DB_main_PASSWORD
      JWT_SECRET: $RANDOM_STRING
      ADMIN_JWT_SECRET: $RANDOM_STRING
      APP_KEYS: $RANDOM_STRING
      API_TOKEN_SALT: $RANDOM_STRING
      TRANSFER_TOKEN_SALT: $RANDOM_STRING
      NODE_ENV: production
databases:
  - type: mariadb
    id: main
    version: 10.6.8
    bundlePlanID: standard
    planID: small-g2
