apps:
  - id: "uptime-kuma"
    name: "Uptime Kuma"
    image: "louislam/uptime-kuma:1"
    availableImageTags:
      - "1"
      - "2.0.0-beta.0"    
    bundlePlanID: "standard"
    planID: "small-g2"
    port: 3001
    disks:
      - name: "data"
        mountTo: "/app/data"

    envs:
      UPTIME_KUMA_DB_TYPE: "sqlite"