apps:
  - id: "uptime-kuma"
    name: "Uptime Kuma"
    image: "registry.c2.liara.ir/one-click-apps/louislam/uptime-kuma:1"
    bundlePlanID: "standard"
    planID: "small-g2"
    port: 3001
    disks:
      - name: "data"
        mountTo: "/app/data"
