apps:
  - id: affine
    name: AFFiNE
    image: registry.c2.liara.ir/one-click-apps/affine-graphql:stable-eb0466e
    bundlePlanID: standard
    planID: small-g2
    args:
      - sh
      - '-c'
      - node ./scripts/self-host-predeploy && node ./dist/index.js
    disks:
      - name: config
        mountTo: /root/.affine/config
        size: 10
        maxSize: 2
      - name: storage
        mountTo: /root/.affine/storage
        size: 10
        maxSize: 2
    port: 3010
    envs:
      NODE_OPTIONS: '--import=./scripts/register.js'
      AFFINE_SERVER_HOST: $APP_NAME.liara.run
      AFFINE_SERVER_PORT: '3010'
      AFFINE_SERVER_HTTPS: 'true'
      AFFINE_CONFIG_PATH: /root/.affine/config
      REDIS_SERVER_HOST: $DB_base_HOST
      REDIS_SERVER_PORT: $DB_base_PORT
      REDIS_SERVER_PASSWORD: $DB_base_PASSWORD
      DATABASE_URL: >-
        postgres://$DB_main_USER:$DB_main_PASSWORD@$DB_main_HOST:$DB_main_PORT/postgres
      NODE_ENV: production
      AFFINE_ADMIN_EMAIL: default@example.com
      AFFINE_ADMIN_PASSWORD: $RANDOM_STRING
      TELEMETRY_ENABLE: 'false'
      MAILER_HOST: smtp.c1.liara.email
      MAILER_PORT: '587'
      MAILER_USER: empty-for-now
      MAILER_PASSWORD: empty-for-now
      MAILER_SENDER: admin@example.com
databases:
  - type: postgres
    id: main
    version: '15.4'
    bundlePlanID: standard
    planID: small-g2
  - type: redis
    id: base
    version: 7.2.3
    bundlePlanID: standard
    planID: small-g2
