apps:
  - id: formbricks
    name: formbricks
    image: ghcr.io/formbricks/formbricks:v2.5.3
    bundlePlanID: standard
    planID: small-g2
    port: 3000

    disks:
      - name: uploads
        mountTo: "/home/nextjs/apps/web/uploads/"
        size: 10
        maxSize: 1

    envs:
      WEBAPP_URL: "https://$APP_NAME.liara.run"
      NEXTAUTH_URL: "https://$APP_NAME.liara.run"
      DATABASE_URL: "postgres://$DB_main_USER:$DB_main_PASSWORD@$DB_main_HOST:$DB_main_PORT/postgres"
      NEXTAUTH_SECRET: "$RANDOM_STRING"
      ENCRYPTION_KEY: "48754c6d6eb3f285971b7cc7daa010b242fc75e3d205fb32d364a681823cc9c7"
      CRON_SECRET: "$RANDOM_STRING"
      UPLOADS_DIR: "/home/nextjs/apps/web/uploads/"
      EMAIL_VERIFICATION_DISABLED: "1"

databases:
  - type: postgres
    id: main
    version: '15.4'
    bundlePlanID: standard
    planID: small-g2
